server:
  port: 7001

eureka:
  instance:
    hostname: erueka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://erueka7002.com:7002/eureka/
      defaultZone: http://erueka7001.com:7001/eureka/, http://erueka7002.com:7002/eureka/