server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-openfeign

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://erueka7001.com:7001/eureka/, http://erueka7002.com:7002/eureka/
  instance:
    instance-id: order-openfeign80
    prefer-ip-address: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    cn.morooi.springcloud.service.PaymentFeignService: debug

