#person:
#  last-name: 张三{random.uuid}
#  age: 18
#  boss: false
#  birth: 2020/2/23
#  maps: {k1: v1, k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#    - wangwu
#  dog:
#    name: ${person.last-name}-小狗
#    age: 3
#
#server:
#  port: 8081
